### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by vdbhb59** [pawitp/android_kernel_samsung_i9082#4]
Hi Mate (Prasan),
You may not remember me, but I was one of the avid users of CM and a die hard fan of yours back in CM days till you stopped with April build for I9082. I wish to rebuild for many users who still hold I9082 and are in dire need of some change for many reasons.
How would I be able to approach you mate?
I can see https://github.com/pawitp/android_device_samsung_i9082 & https://github.com/pawitp/android_kernel_samsung_i9082 from your repos. However, do you have the manifest I can use to build? Would be really helpful mate. Also, if your sources..

Also, apologies, was not sure how I could reach you, so opening one like this.

Awaiting your response mate.

**Comment by vdbhb59** [comment]
Is this the manifest: https://github.com/CyanogenMod/android ? Does this still hold good to build fully?
Sorry if asking too many questions.

**Comment by pawitp** [comment]
I'm not sure of the state, but you should be able to checkout that manifest, add these two repos as extra, extract needed files from device and build.
